Create codeql-analysis.yml
frankvdbroek/BouncerNg pull request #11
Opened 2021-12-28 00:26 UTC by Hayyan55

Ik denk dat het handig zou zijn om dit workflow file te gebruiken aan gezien dat automatisch common kwetsbaarheden en Coderen fouten kan detecteren.

P.S. Google: "CodeQL"

2021-12-28 14:17 UTC, frankvdbroek commented on .github/workflows/codeql-analysis.yml
> +        language: [ 'javascript' ]
Zullen we hier ook typescript bij zetten?

2021-12-29 12:16 UTC, Hayyan55 commented on .github/workflows/codeql-analysis.yml
> +        language: [ 'javascript' ]
Ik heb inderdaad Typescript toegevoegd en hij begon meteen zijn taak te doen. Nu is hij wel prima denk ik.

2022-01-12 08:25 UTC, frankvdbroek requested changes

2022-01-12 08:25 UTC, frankvdbroek commented on .github/workflows/codeql-analysis.yml
> +        language: [ 'javascript', 'typescupt' ]
Zit een typo in `typescript`

2022-01-13 10:34 UTC, AlexBor223 reviewed
LGTM

2022-01-13 10:35 UTC, AlexBor223 approved these changes

2022-01-17 08:32 UTC, frankvdbroek approved these changes

2022-01-17 08:32 UTC, merged